# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
