# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 03:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='answered_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 12, 3, 51, 28, 944487, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=django_light_enums.db.EnumField(choices=[(10, 'SINGLE_ANSWER'), (20, 'MULTIPLE_CHOICE')], default=10, enum_values=(10, 20)),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
