# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0002_auto_20170211_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
