# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0002_auto_20170122_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vector',
            old_name='xComponent',
            new_name='x_component',
        ),
        migrations.RenameField(
            model_name='vector',
            old_name='yComponent',
            new_name='y_component',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='module',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='unit',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
