# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 03:29
from __future__ import unicode_literals

from django.db import migrations
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0003_auto_20170123_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=django_light_enums.db.EnumField(choices=[(10, 'VECTOR'), (20, 'MULTIPLE_CHOICE')], default=10, enum_values=(10, 20)),
        ),
    ]
