# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0003_auto_20170218_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'db_table': 'curricula_images',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=django_light_enums.db.EnumField(choices=[(40, 'IMAGE'), (0, 'UNDEFINED'), (10, 'TEXT'), (20, 'VECTOR'), (30, 'NULLABLE_VECTOR')], default=0, enum_values=(40, 0, 10, 20, 30)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=django_light_enums.db.EnumField(choices=[(0, 'UNDEFINED'), (10, 'SINGLE_ANSWER'), (20, 'MULTIPLE_CHOICE')], default=0, enum_values=(0, 10, 20)),
        ),
    ]
