# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 03:30
from __future__ import unicode_literals

from django.db import migrations
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0004_question_answer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=django_light_enums.db.EnumField(choices=[(0, 'UNSPECIFIED'), (10, 'VECTOR'), (20, 'MULTIPLE_CHOICE')], default=0, enum_values=(0, 10, 20)),
        ),
    ]
