# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 05:07
from __future__ import unicode_literals

from django.db import migrations
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_sound_enabled'),
        ('curricula', '0004_auto_20170220_0021'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together=set([('profile', 'lesson')]),
        ),
    ]
