# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 23:37
from __future__ import unicode_literals

from django.db import migrations
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0006_auto_20170306_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='status',
            field=django_light_enums.db.EnumField(choices=[(0, 'LOCKED'), (10, 'NEW'), (20, 'UNLOCKED'), (30, 'COMPLETE')], default=0, enum_values=(0, 10, 20, 30)),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=django_light_enums.db.EnumField(choices=[(0, 'UNDEFINED'), (40, 'IMAGE'), (10, 'TEXT'), (20, 'VECTOR'), (30, 'NULLABLE_VECTOR')], default=0, enum_values=(0, 40, 10, 20, 30)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=django_light_enums.db.EnumField(choices=[(0, 'UNDEFINED'), (10, 'SINGLE_ANSWER'), (20, 'MULTIPLE_CHOICE')], default=0, enum_values=(0, 10, 20)),
        ),
    ]
