# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pib', '0006_auto_20170110_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='curriculum',
            old_name='curriculum_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='pub_date',
            new_name='published_on',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='module_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='module_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='pub_date',
            new_name='published_on',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='pub_date',
            new_name='published_on',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='unit_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='pub_date',
            new_name='published_on',
        ),
    ]
