# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 05:08
from __future__ import unicode_literals

from django.db import migrations
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0006_auto_20170123_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=django_light_enums.db.EnumField(choices=[(10, 'SINGLE_ANSWER'), (20, 'MULTIPLE_CHOICES')], default=10, enum_values=(10, 20)),
        ),
    ]
