# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_light_enums.db
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0007_auto_20170417_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'db_table': 'curricula_games',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=django_light_enums.db.EnumField(choices=[(0, 'DEFAULT'), (1, 'GAME')], default=0, enum_values=(0, 1)),
        ),
        migrations.AddField(
            model_name='game',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='curricula.Lesson'),
        ),
    ]
