# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 03:44
from __future__ import unicode_literals

from django.db import migrations
import django_light_enums.db
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0007_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
        migrations.AddField(
            model_name='lesson',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
        migrations.AddField(
            model_name='module',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
        migrations.AddField(
            model_name='question',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
        migrations.AddField(
            model_name='unit',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=django_light_enums.db.EnumField(choices=[(10, 'SINGLE_ANSWER'), (20, 'MULTIPLE_CHOICE')], default=10, enum_values=(10, 20)),
        ),
    ]
