# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0008_auto_20170419_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathematicalExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('representation', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'curricula_mathematical_expressions',
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=django_light_enums.db.EnumField(choices=[(0, 'UNDEFINED'), (50, 'MATHEMATICAL_EXPRESSION'), (20, 'VECTOR'), (40, 'IMAGE'), (10, 'TEXT'), (30, 'NULLABLE_VECTOR')], default=0, enum_values=(0, 50, 20, 40, 10, 30)),
        ),
    ]
