# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0009_auto_20170203_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=django_light_enums.db.EnumField(choices=[(10, 'SINGLE_ANSWER'), (20, 'MULTIPLE_CHOICE')], default=10, enum_values=(10, 20)),
        ),
        migrations.AlterField(
            model_name='vector',
            name='angle',
            field=models.FloatField(blank=True, null=True, verbose_name='Angle'),
        ),
        migrations.AlterField(
            model_name='vector',
            name='magnitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Magnitude'),
        ),
        migrations.AlterField(
            model_name='vector',
            name='x_component',
            field=models.FloatField(blank=True, null=True, verbose_name='x-Component'),
        ),
        migrations.AlterField(
            model_name='vector',
            name='y_component',
            field=models.FloatField(blank=True, null=True, verbose_name='y-Component'),
        ),
    ]
