# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 03:20
from __future__ import unicode_literals

from django.db import migrations
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0009_auto_20170425_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=django_light_enums.db.EnumField(choices=[(0, 'UNDEFINED'), (50, 'MATHEMATICAL_EXPRESSION'), (20, 'VECTOR'), (40, 'IMAGE'), (10, 'TEXT'), (60, 'VECTOR_COMPONENTS'), (30, 'NULLABLE_VECTOR')], default=0, enum_values=(0, 50, 20, 40, 10, 60, 30)),
        ),
    ]
