# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0010_auto_20170508_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='vectors',
            field=models.ManyToManyField(related_name='questions', to='curricula.Vector'),
        ),
    ]
