# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0013_auto_20171127_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=django_light_enums.db.EnumField(choices=[(0, 'DEFAULT'), (1, 'GAME')], default=0, enum_values=(0, 1)),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='status',
            field=django_light_enums.db.EnumField(choices=[(0, 'LOCKED'), (10, 'NEW'), (20, 'UNLOCKED'), (30, 'COMPLETE')], default=0, enum_values=(0, 10, 20, 30)),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=django_light_enums.db.EnumField(choices=[(0, 'UNDEFINED'), (50, 'MATHEMATICAL_EXPRESSION'), (20, 'VECTOR'), (70, 'UNIT_CONVERSION'), (40, 'IMAGE'), (10, 'TEXT'), (60, 'VECTOR_COMPONENTS'), (30, 'NULLABLE_VECTOR')], default=0, enum_values=(0, 50, 20, 70, 40, 10, 60, 30)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=django_light_enums.db.EnumField(choices=[(0, 'UNDEFINED'), (10, 'SINGLE_ANSWER'), (20, 'MULTIPLE_CHOICE')], default=0, enum_values=(0, 10, 20)),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='answer',
            field=models.CharField(help_text='Correct answer with unit: m, s, kg, m/s', max_length=100),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='denominator',
            field=models.CharField(blank=True, help_text='Denominator value with unit: m, s, kg, m/s', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='numerator',
            field=models.CharField(blank=True, help_text='Numerator value with unit: m, s, kg, m/s', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='show_answer',
            field=models.BooleanField(default=True, help_text='Set for showing answer, otherwise show fraction'),
        ),
    ]
