# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 04:29
from __future__ import unicode_literals

from django.db import migrations
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0019_auto_20180227_1304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=django_light_enums.db.EnumField(choices=[(0, 'DEFAULT'), (1, 'GAME')], default=0, enum_values=(0, 1)),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='status',
            field=django_light_enums.db.EnumField(choices=[(0, 'LOCKED'), (10, 'NEW'), (20, 'UNLOCKED'), (30, 'COMPLETE')], default=0, enum_values=(0, 10, 20, 30)),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=django_light_enums.db.EnumField(choices=[(0, 'UNDEFINED'), (50, 'MATHEMATICAL_EXPRESSION'), (100, 'MULTIPLE_CHOICE'), (30, 'NULLABLE_VECTOR'), (70, 'UNIT_CONVERSION'), (20, 'VECTOR'), (60, 'VECTOR_COMPONENTS'), (110, 'MULTISELECT_CHOICE')], default=0, enum_values=(0, 50, 100, 30, 70, 20, 60, 110)),
        ),
    ]
