# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-01 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_light_enums.db


def set_author(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Curriculum = apps.get_model('curricula', 'Curriculum')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Curriculum.objects.update(author=User.objects.filter(is_superuser=True).order_by('id')[0])

class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0022_auto_20180601_1045'),
    ]

    operations = [
        migrations.RunPython(set_author),
        migrations.AlterField(
            model_name='curriculum',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
