# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0023_auto_20180601_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='curricula.Question'),
        ),
    ]
