# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 12:22
from __future__ import unicode_literals

from django.db import migrations
import django_light_enums.db
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0024_auto_20180606_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitconversion',
            name='conversion_steps',
            field=jsonfield.fields.JSONField(blank=True, default=[], help_text='Numerator/Denominator steps', null=True),
        ),
    ]
