# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-12 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django_light_enums.db
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curricula', '0025_auto_20180606_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='collaborators',
            field=models.ManyToManyField(related_name='coauthored_curricula', to=settings.AUTH_USER_MODEL),
        ),
    ]
