# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-02 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0029_auto_20180927_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='number_of_learners_denormalized',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
