# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-06 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0030_auto_20181002_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='collaborators',
            field=models.ManyToManyField(related_name='coauthored_curricula', to='profiles.Profile'),
        ),
    ]
