# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-09 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0031_auto_20181006_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='setting_lessons_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='setting_modules_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='setting_publically',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='setting_units_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
