# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 05:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curricula', '0036_auto_20190323_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAwards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_completed_award', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleAwards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_finished_badge', models.BooleanField(default=False)),
                ('module_completed_award', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curricula.Module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='lessonbadges',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lessonbadges',
            name='user',
        ),
        migrations.RemoveField(
            model_name='modulebadges',
            name='module',
        ),
        migrations.RemoveField(
            model_name='modulebadges',
            name='user',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=django_light_enums.db.EnumField(choices=[(0, 'DEFAULT'), (1, 'GAME')], default=0, enum_values=(0, 1)),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='status',
            field=django_light_enums.db.EnumField(choices=[(0, 'LOCKED'), (10, 'NEW'), (20, 'UNLOCKED'), (30, 'COMPLETE')], default=0, enum_values=(0, 10, 20, 30)),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=django_light_enums.db.EnumField(choices=[(0, 'UNDEFINED'), (100, 'MULTIPLE_CHOICE'), (110, 'MULTISELECT_CHOICE'), (20, 'VECTOR'), (30, 'NULLABLE_VECTOR'), (50, 'MATHEMATICAL_EXPRESSION'), (60, 'VECTOR_COMPONENTS'), (70, 'UNIT_CONVERSION')], default=0, enum_values=(0, 100, 110, 20, 30, 50, 60, 70)),
        ),
        migrations.DeleteModel(
            name='LessonBadges',
        ),
        migrations.DeleteModel(
            name='ModuleBadges',
        ),
        migrations.AddField(
            model_name='lessonawards',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curricula.Lesson'),
        ),
        migrations.AddField(
            model_name='lessonawards',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
