# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0037_auto_20190419_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'curricula_text',
            },
        ),
    ]
