# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-13 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0039_auto_20190612_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solution_text',
            field=models.CharField(blank=True, db_index=True, max_length=2048, null=True),
        ),
    ]
