# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-25 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0041_auto_20190618_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysql',
            name='schema_is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
