# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-02 05:42
from __future__ import unicode_literals

from django.db import migrations
import django_light_enums.db
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0042_auto_20190625_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysql',
            name='expected_output_json',
            field=jsonfield.fields.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='mysql',
            name='schema_SQL_json',
            field=jsonfield.fields.JSONField(default=None),
        ),
    ]
