# Generated by Django 2.2.3 on 2019-09-20 07:53

from django.db import migrations, models
import django.db.models.deletion
import django_light_enums.db
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('curricula', '0043_auto_20190702_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='anon_session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='session key'),
        ),
        migrations.AddField(
            model_name='module',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='unit',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='anon_session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='session key'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='setting_lessons_unlocked',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='setting_modules_unlocked',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='setting_publically',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='setting_units_unlocked',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=django_light_enums.db.EnumField(choices=[(0, 'DEFAULT'), (1, 'GAME')], default=0, enum_values=(0, 1)),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='status',
            field=django_light_enums.db.EnumField(choices=[(0, 'LOCKED'), (10, 'NEW'), (20, 'UNLOCKED'), (30, 'COMPLETE')], default=0, enum_values=(0, 10, 20, 30)),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=django_light_enums.db.EnumField(choices=[(0, 'UNDEFINED'), (100, 'MULTIPLE_CHOICE'), (110, 'MULTISELECT_CHOICE'), (20, 'VECTOR'), (30, 'NULLABLE_VECTOR'), (50, 'MATHEMATICAL_EXPRESSION'), (60, 'VECTOR_COMPONENTS'), (70, 'UNIT_CONVERSION'), (80, 'TEXT'), (90, 'MYSQL')], default=0, enum_values=(0, 100, 110, 20, 30, 50, 60, 70, 80, 90)),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='profiles.Profile'),
        ),
    ]
