# Generated by Django 2.2.15 on 2020-11-08 10:25

import curricula.models.answers
import django.contrib.postgres.fields.jsonb
from django.db import migrations
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0045_auto_20201108_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitconversion',
            name='conversion_steps',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=curricula.models.answers.jsonfield_default_value, help_text='Numerator/Denominator steps', null=True),
        ),
    ]
