# Generated by Django 2.2.20 on 2021-05-04 14:34

from django.db import migrations
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0046_auto_20201108_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=django_light_enums.db.EnumField(choices=[(0, 'DEFAULT'), (1, 'GAME')], default=0, enum_values=(0, 1)),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='status',
            field=django_light_enums.db.EnumField(choices=[(0, 'LOCKED'), (10, 'NEW'), (20, 'UNLOCKED'), (30, 'COMPLETE')], default=0, enum_values=(0, 10, 20, 30)),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=django_light_enums.db.EnumField(choices=[(0, 'UNDEFINED'), (100, 'MULTIPLE_CHOICE'), (110, 'MULTISELECT_CHOICE'), (20, 'VECTOR'), (30, 'NULLABLE_VECTOR'), (50, 'MATHEMATICAL_EXPRESSION'), (60, 'VECTOR_COMPONENTS'), (70, 'UNIT_CONVERSION'), (80, 'TEXT'), (90, 'MYSQL')], default=0, enum_values=(0, 100, 110, 20, 30, 50, 60, 70, 80, 90)),
        ),
    ]
