# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sound_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
