# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-16 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_all_lessons_unlocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gravatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
