# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-11 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_gravatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='selected_avatar',
            field=models.CharField(blank=True, choices=[('u', 'User avatar'), ('g', 'Google avatar'), ('a', 'Gravatar')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
