// notifications
export const NOTIFICATIONS_RECEIVE_NOTIFICATIONS = 'NOTIFICATIONS_RECEIVE_NOTIFICATIONS'
export const NOTIFICATIONS_SET_CANCEL_SOURCE = 'NOTIFICATIONS_SET_CANCEL_SOURCE'
export const NOTIFICATIONS_RECEIVE_UNREAD_COUNT = 'NOTIFICATIONS_RECEIVE_UNREAD_COUNT'

// profile
export const PROFILE_RECEIVE_ME = 'PROFILE_RECEIVE_ME'
