{{
   "question":{{
      "content":{{
         "text":{question_text},
         "evaluatedMathText":"",
         "image":{question_image},
         "hint":{question_hint}
      }},
      "type":"base"
   }},
   "answer":{{
      "content":{{
         "text":{answer_text},
         "evaluatedMathText":{answer_evaluated_math_text},
         "image":"",
         "hint":""
      }},
      "type":"base"
   }},
   "hiddenFields":{{
      "answer":{{
         "content":{{
            "evaluatedMathText":"",
            "text":"",
            "image":"",
            "hint":""
         }},
         "type":"base"
      }}
   }}
}}