{
   "question":{
      "content":{
         "text":{question_text},
         "evaluatedMathText":"",
         "image":{question_image},
         "hint":{question_hint}
      },
      "type":"base"
   },
   "hiddenFields":{

   },
   "conversionSteps":{conversion_steps},
   "questionStepNumber":{question_step_number},
   "questionStepUnit":{question_step_unit},
   "questionStepSI":null,
   "answerStepNumber":{answer_step_number},
   "answerStepUnit":{answer_step_unit},
   "answerStepSI":null,
   "conversionType":{conversion_type}
}