{{
   "question":{{
      "content":{{
         "text":{question_text},
         "evaluatedMathText":"",
         "image":"",
         "hint":""
      }},
      "type":"base"
   }},
   "answer":{{
      "content":{{
         "text":"",
         "evaluatedMathText":"",
         "image":"",
         "hint":""
      }},
      "type":"base"
   }},
   "questionTextOnly":{question_text_only},
   "questionVectorIsNull":false,
   "hiddenFields":{{
      "answerVectors":[

      ],
      "answer":{{
         "content":{{
            "text":"",
            "evaluatedMathText":"",
            "image":"",
            "hint":""
         }},
         "type":"base"
      }}
   }},
   "questionVectors": {question_vectors},
   "answerVectors": {answer_vectors},
   "answerVectorIsNull":false,
   "answerTextOnly":{answer_text_only},
   "answerNullableVector":false,
   "answerToCheck":10
}}
