// profile
export const PROFILE_RECEIVE_ME = 'PROFILE_RECEIVE_ME'
export const PROFILE_RECEIVE_PROFILE = 'PROFILE_RECEIVE_PROFILE'
export const PROFILE_FETCHING_PROFILE = 'PROFILE_FETCHING_PROFILE'

// tabs
export const CHANGE_SELECTED_TAB = 'CHANGE_SELECTED_TAB'

// notifications
export const NOTIFICATIONS_RECEIVE_NOTIFICATIONS = 'NOTIFICATIONS_RECEIVE_NOTIFICATIONS'
