# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PiB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
                ('lesson_image', models.ImageField(upload_to=b'')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PiB.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
                ('module_image', models.ImageField(upload_to=b'')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PiB.Lesson')),
            ],
        ),
        migrations.AlterModelOptions(
            name='curriculum',
            options={'verbose_name_plural': 'curricula'},
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PiB.Question'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='question',
            order_with_respect_to='lesson',
        ),
        migrations.AlterOrderWithRespectTo(
            name='lesson',
            order_with_respect_to='module',
        ),
        migrations.AlterOrderWithRespectTo(
            name='choice',
            order_with_respect_to='question',
        ),
    ]
