# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PiB', '0002_auto_20170106_0120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='choice',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name=b'Position'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name=b'Position'),
        ),
        migrations.AddField(
            model_name='module',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name=b'Position'),
        ),
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name=b'Position'),
        ),
        migrations.AddField(
            model_name='unit',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name=b'Position'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='question',
            name='module_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterOrderWithRespectTo(
            name='choice',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='lesson',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='module',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='question',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='unit',
            order_with_respect_to=None,
        ),
    ]
