# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PiB', '0003_auto_20170106_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawVector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('magnitude', models.PositiveSmallIntegerField(null=True, verbose_name=b'Magnitude')),
                ('angle', models.PositiveSmallIntegerField(null=True, verbose_name=b'Angle')),
                ('xComponent', models.SmallIntegerField(null=True, verbose_name=b'Angle')),
                ('yComponent', models.SmallIntegerField(null=True, verbose_name=b'Angle')),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
                ('image', models.ImageField(blank=True, upload_to=b'')),
                ('position', models.PositiveSmallIntegerField(null=True, verbose_name=b'Position')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PiB.Lesson')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.RenameField(
            model_name='question',
            old_name='module_image',
            new_name='image',
        ),
    ]
