export const CHANGE_SELECTED_TAB = 'CHANGE_SELECTED_TAB';
export const CLASSROOM_RECEIVE_CLASSROOM_LIST = 'CLASSROOM_RECEIVE_CLASSROOM_LIST'
// TODO remove
export const DATA_FETCH_PROTECTED_DATA_REQUEST = 'DATA_FETCH_PROTECTED_DATA_REQUEST'
export const DATA_RECEIVE_PROTECTED_DATA = 'DATA_RECEIVE_PROTECTED_DATA'
