export const CHANGE_SELECTED_TAB = 'CHANGE_SELECTED_TAB'
export const CLASSROOM_RECEIVE_CLASSROOMS_LIST = 'CLASSROOM_RECEIVE_CLASSROOMS_LIST'
export const CLASSROOM_CREATE_CLASSROOM_SUCCESS = 'CLASSROOM_CREATE_CLASSROOM_SUCCESS'
export const CURRICULA_RECEIVE_CURRICULA_LIST = 'CURRICULA_RECEIVE_CURRICULA_LIST'
export const CURRICULA_RECEIVE_OTHER_CURRICULA_LIST = 'CURRICULA_RECEIVE_OTHER_CURRICULA_LIST'
// TODO remove
export const DATA_FETCH_PROTECTED_DATA_REQUEST = 'DATA_FETCH_PROTECTED_DATA_REQUEST'
export const DATA_RECEIVE_PROTECTED_DATA = 'DATA_RECEIVE_PROTECTED_DATA'
