// reputation
export const REPUTATION_ACTIONS_RECEIVE_REPUTATION_ACTIONS = 'REPUTATION_ACTIONS_RECEIVE_REPUTATION_ACTIONS'
export const REPUTATION_ACTIONS_SET_CANCEL_SOURCE = 'REPUTATION_ACTIONS_SET_CANCEL_SOURCE'
export const REPUTATION_ACTIONS_RECEIVE_UNREAD_COUNT = 'REPUTATION_ACTIONS_RECEIVE_UNREAD_COUNT'

// profile
export const PROFILE_RECEIVE_ME = 'PROFILE_RECEIVE_ME'
