export const RESOURCE_RECEIVE_RESOURCE_OPTIONS = 'RESOURCE_RECEIVE_RESOURCE_OPTIONS'
export const CREATE_RESOURCE_SUCCESS = 'CREATE_RESOURCE_SUCCESS'
export const RESOURCE_RECEIVE_POPULAR_RESOURCES = 'RESOURCE_RECEIVE_POPULAR_RESOURCES'
export const RESOURCE_RECEIVE_RECENT_RESOURCES = 'RESOURCE_RECEIVE_RECENT_RESOURCES'
export const RESOURCE_RECEIVE_NEW_RESOURCES = 'RESOURCE_RECEIVE_NEW_RESOURCES'
export const RESOURCE_RECEIVE_RESOURCE = 'RESOURCE_RECEIVE_RESOURCE'
export const RESOURCE_RECEIVE_PROBLEM = 'RESOURCE_RECEIVE_PROBLEM'
export const RESOURCE_RECEIVE_SOLUTION = 'RESOURCE_RECEIVE_SOLUTION'

// google
export const GOOGLE_RECEIVE_BOOKS_LIST = 'GOOGLE_RECEIVE_BOOKS_LIST'
export const GOOGLE_INIT_STATE_CHANGED = 'GOOGLE_INIT_STATE_CHANGED'

// djeddit
export const DJEDDIT_RECEIVE_THREAD = 'DJEDDIT_RECEIVE_THREAD'
