export const RESOURCE_RECEIVE_RESOURCE_OPTIONS = 'RESOURCE_RECEIVE_RESOURCE_OPTIONS'
export const CREATE_RESOURCE_SUCCESS = 'CREATE_RESOURCE_SUCCESS'

// google
export const GOOGLE_RECEIVE_BOOKS_LIST = 'GOOGLE_RECEIVE_BOOKS_LIST'
export const GOOGLE_INIT_STATE_CHANGED = 'GOOGLE_INIT_STATE_CHANGED'

