# Generated by Django 2.2.8 on 2020-01-17 14:56

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_profile_views'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialProblemTypeSandbox',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Name', max_length=2048, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(blank=True, max_length=1536, null=True, unique=True)),
                ('slug_prefix', models.SlugField(blank=True, max_length=1536, null=True)),
                ('slug_suffix', models.PositiveIntegerField(null=True)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Position')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('git', models.URLField(blank=True, null=True)),
                ('external_resources', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('npm_dependencies', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('is_sse', models.BooleanField(blank=True, default=False, null=True)),
                ('entry', models.TextField()),
                ('screenshot_url', models.URLField(blank=True, null=True)),
                ('picks', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('template', models.TextField(default='create-react-app')),
                ('description', models.TextField(blank=True, null=True)),
                ('custom_template', models.TextField(blank=True, null=True)),
                ('forked_template', models.TextField(blank=True, null=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('forked_from_sandbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.MaterialProblemTypeSandbox')),
                ('last_edit_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_materialproblemtypesandbox_last_edit_items', to='profiles.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialProblemTypeSandboxDirectory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Name', max_length=2048, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(blank=True, max_length=1536, null=True, unique=True)),
                ('slug_prefix', models.SlugField(blank=True, max_length=1536, null=True)),
                ('slug_suffix', models.PositiveIntegerField(null=True)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Position')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('directory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.MaterialProblemTypeSandboxDirectory')),
                ('last_edit_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_materialproblemtypesandboxdirectory_last_edit_items', to='profiles.Profile')),
                ('sandbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='courses.MaterialProblemTypeSandbox')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialProblemTypeSandboxModule',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Name', max_length=2048, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(blank=True, max_length=1536, null=True, unique=True)),
                ('slug_prefix', models.SlugField(blank=True, max_length=1536, null=True)),
                ('slug_suffix', models.PositiveIntegerField(null=True)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Position')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('code', models.TextField()),
                ('is_binary', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('directory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='courses.MaterialProblemTypeSandboxDirectory')),
                ('last_edit_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_materialproblemtypesandboxmodule_last_edit_items', to='profiles.Profile')),
                ('sandbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.MaterialProblemTypeSandbox')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MaterialProblemType',
        ),
        migrations.CreateModel(
            name='MaterialProblemType',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.materialproblemtypesandbox',),
        ),
    ]
