# Generated by Django 2.2.11 on 2020-03-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200128_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialproblemtypesandbox',
            name='screenshot_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='materialproblemtypesandboxmodule',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
