# Generated by Django 2.2.15 on 2020-09-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_jsondataimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='complete_boundary',
            field=models.PositiveSmallIntegerField(default=80, verbose_name='Lesson complete boundary (percent)'),
        ),
    ]
