# Generated by Django 2.2.15 on 2021-03-09 12:47

import courses.models.material
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20210217_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsondataimage',
            name='material',
        ),
        migrations.AlterField(
            model_name='material',
            name='material_workflow_type',
            field=models.IntegerField(choices=[(10, courses.models.material.MaterialWorkflowType(10)), (20, courses.models.material.MaterialWorkflowType(20)), (80, courses.models.material.MaterialWorkflowType(80)), (90, courses.models.material.MaterialWorkflowType(90))], default=10),
        ),
    ]
