# Generated by Django 2.2.15 on 2021-03-29 08:22

import courses.models.material_problem_type_sandbox
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20210309_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialproblemtypesandboxcache',
            name='data',
            field=models.FileField(upload_to=courses.models.material_problem_type_sandbox.data_upload_to),
        ),
    ]
