# Generated by Django 2.2.15 on 2021-04-01 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20210329_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialproblemtypesandboxcache',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
