# Generated by Django 2.2.24 on 2021-08-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20210624_0407'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialproblemtypesandboxdirectory',
            unique_together={('sandbox', 'shortid')},
        ),
        migrations.AlterUniqueTogether(
            name='materialproblemtypesandboxmodule',
            unique_together={('sandbox', 'shortid')},
        ),
    ]
