# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-27 06:02
from __future__ import unicode_literals

from django.db import migrations


def generate_display_names(apps, schema_editor):
    '''
    Generate display names for all the users without one
    '''
    User = apps.get_model('pib_auth', 'User')
    for user in User.objects.all():
        if not user.display_name:
            if user.first_name and user.last_name:
                user.display_name = '{} {}'.format(user.first_name, user.last_name)
                user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pib_auth', '0004_user_display_name'),
    ]

    operations = [
        migrations.RunPython(generate_display_names)
    ]
