# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-17 07:01
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify


def generate_username(apps, schema_editor):
    '''
    Generate a username given the first and last name.
    Ex. Bill Gates -> bill_gates
    '''
    Users = apps.get_model('pib_auth', 'User')

    usernames = []
    for user in Users.objects.all():
        if not user.username:
            pre_username = '{}_{}'.format(user.first_name.strip(), user.last_name.strip())  # bill_gates
            post_username = pre_username  # will become something like bill_gates2

            username_not_unique = True

            # We need to make sure this is unique
            counter = 0
            while username_not_unique:
                counter += 1
                username_not_unique = False
                for another_user in Users.objects.all():
                    if another_user.username == post_username:
                        username_not_unique = True
                        post_username = '{}{}'.format(pre_username, counter)
                        break
            user.username = post_username
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pib_auth', '0004_user_username'),
    ]

    operations = [
        migrations.RunPython(generate_username)
    ]
