from __future__ import unicode_literals
from django.db import models


class NcesDb(models.Model):
    index = models.IntegerField(primary_key=True)
    academicyear = models.IntegerField(blank=True, null=True)
    unitid = models.IntegerField(blank=True, null=True)
    instname = models.TextField(blank=True, null=True)
    city = models.TextField(blank=True, null=True)
    state = models.TextField(blank=True, null=True)
    zip = models.TextField(blank=True, null=True)
    sector_revised = models.IntegerField(blank=True, null=True)
    iclevel = models.IntegerField(blank=True, null=True)
    control = models.IntegerField(blank=True, null=True)
    oberegion = models.IntegerField(blank=True, null=True)
    census_division = models.IntegerField(blank=True, null=True)
    census_region = models.IntegerField(blank=True, null=True)
    flagship = models.IntegerField(blank=True, null=True)
    landgrnt = models.IntegerField(blank=True, null=True)
    hbcu = models.IntegerField(blank=True, null=True)
    hsi = models.IntegerField(blank=True, null=True)
    medical = models.IntegerField(blank=True, null=True)
    hospital = models.IntegerField(blank=True, null=True)
    fte_count = models.FloatField(blank=True, null=True)
    tuition03 = models.FloatField(blank=True, null=True)
    govt_reliance_c = models.FloatField(blank=True, null=True)
    fed_grant_pct = models.FloatField(blank=True, null=True)
    fed_grant_avg_amount = models.FloatField(blank=True, null=True)
    state_grant_pct = models.FloatField(blank=True, null=True)
    state_grant_avg_amount = models.FloatField(blank=True, null=True)
    inst_grant_pct = models.FloatField(blank=True, null=True)
    inst_grant_avg_amount = models.FloatField(blank=True, null=True)
    loan_pct = models.FloatField(blank=True, null=True)
    loan_avg_amount = models.FloatField(blank=True, null=True)
    tuitionfee01_tf = models.FloatField(blank=True, null=True)
    tuitionfee02_tf = models.FloatField(blank=True, null=True)
    tuitionfee03_tf = models.FloatField(blank=True, null=True)
    research01_fasb = models.FloatField(blank=True, null=True)
    gross_operating_margin = models.FloatField(blank=True, null=True)
    assets06 = models.FloatField(blank=True, null=True)
    grad_rate_150_p = models.FloatField(blank=True, null=True)
    ptretention_rate = models.FloatField(blank=True, null=True)
    total_undergraduates = models.FloatField(blank=True, null=True)
    total_graduates = models.FloatField(blank=True, null=True)
    total_enrollment = models.FloatField(blank=True, null=True)
    total_enrollment_amin_tot = models.FloatField(blank=True, null=True)
    total_enrollment_asian_tot = models.FloatField(blank=True, null=True)
    total_enrollment_black_tot = models.FloatField(blank=True, null=True)
    total_enrollment_hisp_tot = models.FloatField(blank=True, null=True)
    total_enrollment_white_tot = models.FloatField(blank=True, null=True)
    total_enrollment_multi_tot = models.FloatField(blank=True, null=True)
    total_enrollment_unkn_tot = models.FloatField(blank=True, null=True)
    total_enrollment_nonres_tot = models.FloatField(blank=True, null=True)
    applcn = models.FloatField(blank=True, null=True)
    applcnm = models.FloatField(blank=True, null=True)
    applcnw = models.FloatField(blank=True, null=True)
    admssn = models.FloatField(blank=True, null=True)
    admssnm = models.FloatField(blank=True, null=True)
    admssnw = models.FloatField(blank=True, null=True)
    actcm25 = models.FloatField(blank=True, null=True)
    actcm75 = models.FloatField(blank=True, null=True)
    acten25 = models.FloatField(blank=True, null=True)
    acten75 = models.FloatField(blank=True, null=True)
    actmt25 = models.FloatField(blank=True, null=True)
    actmt75 = models.FloatField(blank=True, null=True)
    satmt25 = models.FloatField(blank=True, null=True)
    satmt75 = models.FloatField(blank=True, null=True)
    satvr25 = models.FloatField(blank=True, null=True)
    satvr75 = models.FloatField(blank=True, null=True)
    ft_faculty_salary = models.FloatField(blank=True, null=True)

    class Meta:
        db_table = 'nces_db'
