# Generated by Django 2.2.21 on 2021-06-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reputation', '0001_initial'),
    ]

    def remove_reputation_actions(apps, schema_editor):
        ReputationAction = apps.get_model('user_reputation', 'ReputationAction')
        ReputationAction.objects.all().delete()


    operations = [
        migrations.AddField(
            model_name='reputationaction',
            name='new_object_id',
            field=models.UUIDField(db_index=True, null=True, verbose_name='object ID'),
        ),
        migrations.RunPython(remove_reputation_actions),
    ]
