# Generated by Django 2.2.21 on 2021-06-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_reputation', '0003_auto_20210629_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reputationaction',
            name='old_object_id',
        ),
    ]
