# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-27 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_all_lessons_unlocked'),
        ('classroom', '0002_auto_20180719_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomstudent',
            name='leave_on',
        ),
        migrations.AlterUniqueTogether(
            name='classroomstudent',
            unique_together=set([('student', 'classroom')]),
        ),
    ]
