# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-01 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20180727_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='due_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='lessons',
            field=models.ManyToManyField(to='curricula.Lesson'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='start_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
