# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-02 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20180801_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='lessons',
            field=models.ManyToManyField(to='curricula.Module'),
        ),
    ]
