# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-06 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_all_lessons_unlocked'),
        ('classroom', '0005_auto_20180803_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('start_on', models.DateTimeField(auto_now_add=True)),
                ('completed_on', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_progress', to='classroom.Classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_students_assignment_progress', to='profiles.Profile')),
            ],
            options={
                'ordering': ['-start_on'],
            },
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-start_on']},
        ),
    ]
