# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-07 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20180806_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentprogress',
            name='name',
        ),
        migrations.AddField(
            model_name='assignmentprogress',
            name='completed_lessons',
            field=models.ManyToManyField(to='curricula.Lesson'),
        ),
        migrations.AlterField(
            model_name='assignmentprogress',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_progress', to='classroom.Assignment'),
        ),
        migrations.AlterField(
            model_name='assignmentprogress',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
