# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-11 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_all_lessons_unlocked'),
        ('classroom', '0007_auto_20180807_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentprogress',
            name='delayed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentprogress',
            unique_together=set([('assignment', 'student')]),
        ),
    ]
