# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-18 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20180811_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='denormalized_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
