# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-20 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_assignment_denormalized_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentprogress',
            name='start_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
