# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-31 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_auto_20180820_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalClassroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=400)),
                ('teacher_id', models.CharField(max_length=400)),
                ('code', models.CharField(max_length=400)),
                ('provider', models.CharField(choices=[('GC', 'google classrrrom')], default='GC', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='assignmentprogress',
            name='completed_lessons',
            field=models.ManyToManyField(related_name='assignment_progress_completed_lessons', to='curricula.Lesson'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='external_classroom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to='classroom.ExternalClassroom'),
        ),
    ]
