# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-05 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_auto_20180831_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='external_classroom',
        ),
        migrations.AddField(
            model_name='externalclassroom',
            name='classroom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_classroom', to='classroom.Classroom'),
        ),
    ]
