# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-07 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_auto_20180905_1126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='externalclassroom',
            unique_together=set([('external_id', 'provider')]),
        ),
    ]
