# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-08 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_auto_20180907_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalclassroom',
            name='alternate_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
