# Generated by Django 2.2.15 on 2021-02-17 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20210217_0443'),
        ('classroom', '0015_assignment_send_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='courses_lessons',
            field=models.ManyToManyField(to='courses.Lesson'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='externalclassroom',
            name='provider',
            field=models.CharField(choices=[('GC', 'google classroom')], default='GC', max_length=2),
        ),
    ]
