# Generated by Django 2.2.20 on 2021-05-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20210415_1102'),
        ('classroom', '0016_auto_20210217_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentprogress',
            name='completed_courses_lessons',
            field=models.ManyToManyField(related_name='assignment_progress_completed_lessons', to='courses.Lesson'),
        ),

    ]
