# Generated by Django 2.2.20 on 2021-05-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0017_assignmentprogress_completed_courses_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='assignmentprogress',
            name='completed_lessons',
        ),
    ]
