# Generated by Django 2.2.20 on 2021-05-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0018_auto_20210504_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='courses_lessons',
            new_name='lessons',
        ),
        migrations.RenameField(
            model_name='assignmentprogress',
            old_name='completed_courses_lessons',
            new_name='completed_lessons',
        ),
    ]
