# Generated by Django 2.2.20 on 2021-05-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_auto_20210504_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='curriculum',
        ),
    ]
