# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-10 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djeddit', '0008_auto_20181210_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
