# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-16 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djeddit', '0010_auto_20181218_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='djeddit.Topic'),
        ),
        migrations.AlterField(
            model_name='userpostvote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post_votes', to='djeddit.Post'),
        ),
    ]
