# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-17 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djeddit', '0011_auto_20190216_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
