# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-20 09:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('resource_type', models.CharField(choices=[('TB', 'textbook')], default='TB', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='resources.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='TextBookChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('position', models.PositiveSmallIntegerField(verbose_name='Position')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='resources.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='TextBookProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('position', models.PositiveSmallIntegerField(verbose_name='Position')),
                ('textbooksection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='resources.Resource')),
            ],
        ),
    ]
