# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-26 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import resources.validators


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20181126_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBookSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('position', models.PositiveSmallIntegerField(verbose_name='Position')),
            ],
        ),
        migrations.CreateModel(
            name='TextBookSolutionPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='resources/%Y/%m/%d', validators=[resources.validators.validate_pdf_extension])),
            ],
        ),
        migrations.RenameField(
            model_name='textbookproblem',
            old_name='textbooksection',
            new_name='textbook_section',
        ),
        migrations.AddField(
            model_name='textbooksolution',
            name='pdf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='resources.TextBookProblem'),
        ),
        migrations.AddField(
            model_name='textbooksolution',
            name='textbook_problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='resources.TextBookProblem'),
        ),
    ]
