# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-30 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20181128_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbooksolution',
            name='pdf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='resources.TextBookSolutionPDF'),
        ),
    ]
