# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-30 09:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0006_auto_20181130_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbooksolution',
            name='posted_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resources_solutions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
