# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-01 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20180911_1204'),
        ('resources', '0008_auto_20181201_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='profiles.Profile'),
            preserve_default=False,
        ),
    ]
