# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-03 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_resource_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='count_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recentuserresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recent_list', to='resources.Resource'),
        ),
    ]
