# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-08 11:43
from __future__ import unicode_literals

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20181203_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookproblem',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True),
        ),
    ]
