# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-10 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_textbookproblem_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbooksolution',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='textbooksolution',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='textbooksolution',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
