# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-10 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_auto_20181210_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbooksolution',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='textbooksolution',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
