# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-17 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_textbooksolution_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textbookchapter',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='textbookproblem',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='textbooksolution',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='textbooksolution',
            name='count_views',
            field=models.IntegerField(default=0),
        ),
    ]
