# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-24 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_textbooksolution_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbooksolution',
            name='thread',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_book_solutions', to='djeddit.Thread'),
        ),
    ]
