# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-05 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_auto_20181224_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbooksolutionpdf',
            name='external_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='textbooksolution',
            name='thread',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textbook_solution', to='djeddit.Thread'),
        ),
    ]
