# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-14 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20180911_1204'),
        ('resources', '0019_auto_20190105_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookproblem',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources_problems', to='profiles.Profile'),
        ),
    ]
