# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-25 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20180911_1204'),
        ('resources', '0020_textbookproblem_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookchapter',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources_chapter', to='profiles.Profile'),
        ),
    ]
