# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-01 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0021_textbookchapter_posted_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textbooksolution',
            options={'ordering': ['-vote_score']},
        ),
        migrations.AddField(
            model_name='textbookchapter',
            name='show_ad',
            field=models.NullBooleanField(),
        ),
    ]
