# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-16 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0023_auto_20190216_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookproblem',
            name='count_views',
            field=models.IntegerField(default=0),
        ),
    ]
