# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-22 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0024_textbookproblem_count_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
