# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0025_resource_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(blank=True, help_text='title in the admin site', max_length=512, null=True),
        ),
    ]
