# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-24 09:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import resources.validators


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0027_auto_20190424_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardizedTestResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.PositiveIntegerField()),
                ('test_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), resources.validators.max_value_current_year])),
                ('pdf_of_exam', models.FileField(upload_to='resources/standardized_test/%Y/%m/%d', validators=[resources.validators.validate_pdf_extension])),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='standardized_test_info', to='resources.Resource')),
            ],
        ),
        migrations.AddField(
            model_name='resourceproblem',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='resources.Resource'),
        ),
        migrations.AlterField(
            model_name='resourceproblem',
            name='textbook_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='resources.TextBookChapter'),
        ),
    ]
