// profile
export const PROFILE_RECEIVE_ME = 'PROFILE_RECEIVE_ME'

// problemType
export const PROBLEM_TYPES_RECEIVE_PAGINATED_LIST_OBJECT =
  'PROBLEM_TYPES_RECEIVE_PAGINATED_LIST_OBJECT'
export const PROBLEM_TYPES_FETCH_PAGINATED_LIST_OBJECT_REQUEST =
  'PROBLEM_TYPES_FETCH_PAGINATED_LIST_OBJECT_REQUEST'

// courses
export const COURSE_FETCHING_SUCCESS = 'COURSE_FETCHING_SUCCESS'
export const COURSE_FETCHING = 'COURSE_FETCHING'

// modules
export const MODULE_FETCHING_SUCCESS = 'MODULE_FETCHING_SUCCESS'
export const MODULE_FETCHING = 'MODULE_FETCHING'