// profile
export const PROFILE_RECEIVE_ME = 'PROFILE_RECEIVE_ME'

// problemType
export const PROBLEM_TYPES_RECEIVE_LIST = 'PROBLEM_TYPES_RECEIVE_LIST'
export const PROBLEM_TYPES_FETCH_LIST_REQUEST = 'PROBLEM_TYPES_FETCH_LIST_REQUEST'
