// profile
export const PROFILE_RECEIVE_ME = 'PROFILE_RECEIVE_ME'

// problemType
export const PROBLEM_TYPES_RECEIVE_PAGINATED_LIST_OBJECT =
  'PROBLEM_TYPES_RECEIVE_PAGINATED_LIST_OBJECT'
export const PROBLEM_TYPES_FETCH_PAGINATED_LIST_OBJECT_REQUEST =
  'PROBLEM_TYPES_FETCH_PAGINATED_LIST_OBJECT_REQUEST'
