# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_auto_20150513_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgetouser',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
